# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 814)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_video = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_video.setGeometry(QtCore.QRect(20, 10, 961, 751))
        self.groupBox_video.setObjectName("groupBox_video")
        self.label_image = QtWidgets.QLabel(self.groupBox_video)
        self.label_image.setGeometry(QtCore.QRect(0, 30, 960, 540))
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.checkBox_enable_camera = QtWidgets.QCheckBox(self.groupBox_video)
        self.checkBox_enable_camera.setGeometry(QtCore.QRect(640, 730, 101, 22))
        self.checkBox_enable_camera.setObjectName("checkBox_enable_camera")
        self.label_processing_time = QtWidgets.QLabel(self.groupBox_video)
        self.label_processing_time.setGeometry(QtCore.QRect(850, 620, 61, 17))
        self.label_processing_time.setObjectName("label_processing_time")
        self.label_5 = QtWidgets.QLabel(self.groupBox_video)
        self.label_5.setGeometry(QtCore.QRect(730, 620, 120, 17))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_video)
        self.label_4.setGeometry(QtCore.QRect(640, 620, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_fps = QtWidgets.QLabel(self.groupBox_video)
        self.label_fps.setGeometry(QtCore.QRect(670, 620, 67, 17))
        self.label_fps.setObjectName("label_fps")
        self.label_video_status = QtWidgets.QLabel(self.groupBox_video)
        self.label_video_status.setGeometry(QtCore.QRect(750, 710, 121, 20))
        self.label_video_status.setObjectName("label_video_status")
        self.checkBox_enable_detection_yolo = QtWidgets.QCheckBox(self.groupBox_video)
        self.checkBox_enable_detection_yolo.setGeometry(QtCore.QRect(640, 670, 141, 22))
        self.checkBox_enable_detection_yolo.setObjectName("checkBox_enable_detection_yolo")
        self.pushButton_load_video = QtWidgets.QPushButton(self.groupBox_video)
        self.pushButton_load_video.setGeometry(QtCore.QRect(480, 620, 141, 27))
        self.pushButton_load_video.setObjectName("pushButton_load_video")
        self.lineEdit_path_video = QtWidgets.QLineEdit(self.groupBox_video)
        self.lineEdit_path_video.setGeometry(QtCore.QRect(90, 620, 371, 27))
        self.lineEdit_path_video.setObjectName("lineEdit_path_video")
        self.label_2 = QtWidgets.QLabel(self.groupBox_video)
        self.label_2.setGeometry(QtCore.QRect(0, 620, 91, 17))
        self.label_2.setObjectName("label_2")
        self.pushButton_load_graph = QtWidgets.QPushButton(self.groupBox_video)
        self.pushButton_load_graph.setGeometry(QtCore.QRect(480, 650, 141, 27))
        self.pushButton_load_graph.setObjectName("pushButton_load_graph")
        self.label = QtWidgets.QLabel(self.groupBox_video)
        self.label.setGeometry(QtCore.QRect(0, 650, 81, 17))
        self.label.setObjectName("label")
        self.lineEdit_path_graph = QtWidgets.QLineEdit(self.groupBox_video)
        self.lineEdit_path_graph.setGeometry(QtCore.QRect(90, 650, 371, 27))
        self.lineEdit_path_graph.setObjectName("lineEdit_path_graph")
        self.lineEdit_path_cfg_yolo = QtWidgets.QLineEdit(self.groupBox_video)
        self.lineEdit_path_cfg_yolo.setGeometry(QtCore.QRect(90, 680, 371, 27))
        self.lineEdit_path_cfg_yolo.setObjectName("lineEdit_path_cfg_yolo")
        self.pushButton_load_cdg_yolo = QtWidgets.QPushButton(self.groupBox_video)
        self.pushButton_load_cdg_yolo.setGeometry(QtCore.QRect(480, 680, 141, 27))
        self.pushButton_load_cdg_yolo.setObjectName("pushButton_load_cdg_yolo")
        self.label_3 = QtWidgets.QLabel(self.groupBox_video)
        self.label_3.setGeometry(QtCore.QRect(0, 680, 91, 17))
        self.label_3.setObjectName("label_3")
        self.lineEdit_path_weight_yolo = QtWidgets.QLineEdit(self.groupBox_video)
        self.lineEdit_path_weight_yolo.setGeometry(QtCore.QRect(90, 710, 371, 27))
        self.lineEdit_path_weight_yolo.setObjectName("lineEdit_path_weight_yolo")
        self.pushButton_load_weights_yolo = QtWidgets.QPushButton(self.groupBox_video)
        self.pushButton_load_weights_yolo.setGeometry(QtCore.QRect(480, 710, 151, 27))
        self.pushButton_load_weights_yolo.setObjectName("pushButton_load_weights_yolo")
        self.label_6 = QtWidgets.QLabel(self.groupBox_video)
        self.label_6.setGeometry(QtCore.QRect(0, 700, 91, 51))
        self.label_6.setObjectName("label_6")
        self.checkBox_enable_record = QtWidgets.QCheckBox(self.groupBox_video)
        self.checkBox_enable_record.setGeometry(QtCore.QRect(640, 650, 96, 22))
        self.checkBox_enable_record.setObjectName("checkBox_enable_record")
        self.checkBox_enable_detection = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_enable_detection.setGeometry(QtCore.QRect(660, 700, 131, 22))
        self.checkBox_enable_detection.setObjectName("checkBox_enable_detection")
        self.checkBox_enable_playing = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_enable_playing.setGeometry(QtCore.QRect(660, 720, 101, 22))
        self.checkBox_enable_playing.setObjectName("checkBox_enable_playing")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_video.setTitle(_translate("MainWindow", "Video"))
        self.checkBox_enable_camera.setText(_translate("MainWindow", "Camera"))
        self.label_processing_time.setText(_translate("MainWindow", "--/--"))
        self.label_5.setText(_translate("MainWindow", "Processing time:"))
        self.label_4.setText(_translate("MainWindow", "FPS:"))
        self.label_fps.setText(_translate("MainWindow", "--/--"))
        self.label_video_status.setText(_translate("MainWindow", "Status"))
        self.checkBox_enable_detection_yolo.setText(_translate("MainWindow", "Detection YOLO"))
        self.pushButton_load_video.setText(_translate("MainWindow", "Select_video"))
        self.label_2.setText(_translate("MainWindow", "Path to video"))
        self.pushButton_load_graph.setText(_translate("MainWindow", "Select_graph_SSD"))
        self.label.setText(_translate("MainWindow", "Model_CNN"))
        self.pushButton_load_cdg_yolo.setText(_translate("MainWindow", "Select_CFG"))
        self.label_3.setText(_translate("MainWindow", "CFG of YOLO"))
        self.pushButton_load_weights_yolo.setText(_translate("MainWindow", "Select_weights_YOLO"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Weights of </p><p align=\"center\">YOLO</p></body></html>"))
        self.checkBox_enable_record.setText(_translate("MainWindow", "Record"))
        self.checkBox_enable_detection.setText(_translate("MainWindow", "Detection SSD"))
        self.checkBox_enable_playing.setText(_translate("MainWindow", "Play Video"))

